### ISSUE TITLE
Select menu scrolling acts incorrectly.

### ISSUE THREAD

**Issue by emi0x7d1** [Tailus-UI/tailus-ui-react#56]
**Describe the bug**

If you're on mobile, the demo select component is covered by the header which makes it impossible to select the first element if it has by covered. Not sure how to explain it. I will attach a video.

**To Reproduce**

**Expected behavior**

**Screenshots**

https://github.com/Tailus-UI/tailus-ui-react/assets/138755561/4bf39863-1d67-4ee3-9b24-edf09386a6fc

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s22
 - OS: Android
 - Browser: Firefox

**Additional context**

**Comment by Meschacirung** [comment]
I didn't use the `<Portal />` in this example, It's now fixed in the next documentation
