### ISSUE TITLE
[Question] Is there any code for the UI blocks seen at ``ui.tailus.io`` ?

### ISSUE THREAD

**Issue by wanjohiryan** [Tailus-UI/tailus-ui-react#59]
**Is your feature request related to a problem? Please describe.**
Hey there 👋🏾

I'm planning a redesign for a site I'm currently maintaining and, after some research, I discovered these impressive UI components. They look fantastic.

However, I've noticed that the blocks showcased on the site are not available in this public repository.

**Describe the solution you'd like**
No rush, but is there a way to provide examples of blocks with designs similar to those on the site?

**Describe alternatives you've considered**
``ui.shadcn.com/blocks`` 

**Additional context**

**Comment by wanjohiryan** [comment]
Also, what framework are you using to power the ui.tailus docs? 😅

**Comment by Meschacirung** [comment]
The examples (blocks) will be available by the end of the week.
We used Astro and React for the docs

**Comment by wanjohiryan** [comment]
Thank you for the quick reply @Meschacirung 

I will be waiting 👀 :) 

The docs are so beautifully designed and responsive. So you are not using Nextra? 

Hmmm! Did you build it from the ground up or did you use some 3rd party library? I would really love to build my docs website like that.

Once again, thank you

**Comment by Meschacirung** [comment]
Thank you !

Everything is built from scratch :)

**Comment by PJijin** [comment]
> The examples (blocks) will be available by the end of the week. We used Astro and React for the docs

Cool. I'm excited to use that on side project. :)

**Comment by wanjohiryan** [comment]
Hey @Meschacirung 

Pinging you to ask whether the `ui.tailus.io` blocks are available :D

**Comment by Meschacirung** [comment]
Hey @wanjohiryan 

We're launching today ...

**Comment by Meschacirung** [comment]
Now live : ui.tailus.io/examples

**Comment by wanjohiryan** [comment]
🥳🥳🥳finally... thank you so much

**Comment by i-am-henri** [comment]
Is the documentation open source?
